# Generated by Django 4.0.6 on 2022-08-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_authoer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authoer_name',
            new_name='author_name',
        ),
    ]
